"""Initial PostgreSQL financial schema (frozen revision)."""

import sqlalchemy as sa

from alembic import op

revision = "0001_financial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cik", sa.String(length=10), nullable=False),
        sa.Column("legal_name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("cik ~ '^[0-9]{10}$'", name=op.f("ck_companies_cik_format")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
        sa.UniqueConstraint("cik", name=op.f("uq_companies_cik")),
    )
    op.create_table(
        "data_fetch_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("journal_key", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_fetch_logs")),
        sa.UniqueConstraint("journal_key", name=op.f("uq_data_fetch_logs_journal_key")),
    )
    op.create_table(
        "data_source_state",
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("last_attempted_fetch", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_successful_fetch", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_timestamp", sa.Text(), nullable=True),
        sa.Column("data_version", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("source_url", name=op.f("pk_data_source_state")),
    )
    op.create_table(
        "source_objects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("first_fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_timestamp", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_source_objects_hash_format")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_objects")),
        sa.UniqueConstraint(
            "source_url", "content_hash", name=op.f("uq_source_objects_source_url")
        ),
    )
    op.create_table(
        "filings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("accession_number", sa.String(length=20), nullable=False),
        sa.Column("form_type", sa.String(length=12), nullable=False),
        sa.Column("filing_date", sa.Date(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("report_period", sa.Date(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("metadata_source_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "accession_number ~ '^[0-9]{10}-[0-9]{2}-[0-9]{6}$'",
            name=op.f("ck_filings_accession_format"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_filings_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["metadata_source_id"],
            ["source_objects.id"],
            name=op.f("fk_filings_metadata_source_id_source_objects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_filings")),
        sa.UniqueConstraint("company_id", "accession_number", name=op.f("uq_filings_company_id")),
    )
    op.create_index(
        "ix_filings_company_date", "filings", ["company_id", "filing_date"], unique=False
    )
    op.create_table(
        "financial_metrics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("metric_name", sa.String(length=80), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("period_basis", sa.String(length=20), nullable=False),
        sa.Column("value", sa.Numeric(), nullable=True),
        sa.Column("unit", sa.String(length=80), nullable=False),
        sa.Column("formula_version", sa.String(length=40), nullable=False),
        sa.Column("input_set_hash", sa.String(length=64), nullable=False),
        sa.Column("unavailable_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(value IS NULL) = (unavailable_reason IS NOT NULL)",
            name=op.f("ck_financial_metrics_value_or_reason"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_financial_metrics_company_id_companies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_metrics")),
        sa.UniqueConstraint(
            "company_id",
            "metric_name",
            "period_end",
            "period_basis",
            "formula_version",
            "input_set_hash",
            name=op.f("uq_financial_metrics_company_id"),
        ),
    )
    op.create_table(
        "normalization_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("normalization_version", sa.String(length=40), nullable=False),
        sa.Column("accepted_count", sa.Integer(), nullable=False),
        sa.Column("rejected_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('complete','partial')", name=op.f("ck_normalization_runs_status_values")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_normalization_runs_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_objects.id"],
            name=op.f("fk_normalization_runs_source_id_source_objects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_normalization_runs")),
        sa.UniqueConstraint(
            "source_id", "normalization_version", name=op.f("uq_normalization_runs_source_id")
        ),
    )
    op.create_table(
        "securities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_securities_company_id_companies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_securities")),
        sa.UniqueConstraint("ticker", name=op.f("uq_securities_ticker")),
    )
    op.create_table(
        "snapshot_observations",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_objects.id"],
            name=op.f("fk_snapshot_observations_source_id_source_objects"),
        ),
        sa.PrimaryKeyConstraint("source_id", "observed_at", name=op.f("pk_snapshot_observations")),
    )
    op.create_table(
        "financial_statements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("filing_id", sa.UUID(), nullable=False),
        sa.Column("statement_type", sa.String(length=24), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("period_basis", sa.String(length=20), nullable=False),
        sa.Column("unit", sa.String(length=80), nullable=False),
        sa.Column("context_hash", sa.String(length=64), nullable=False),
        sa.Column("normalization_version", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "period_start IS NULL OR period_start <= period_end",
            name=op.f("ck_financial_statements_period_order"),
        ),
        sa.ForeignKeyConstraint(
            ["filing_id"], ["filings.id"], name=op.f("fk_financial_statements_filing_id_filings")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_statements")),
        sa.UniqueConstraint(
            "filing_id",
            "statement_type",
            "context_hash",
            "normalization_version",
            name=op.f("uq_financial_statements_filing_id"),
        ),
    )
    op.create_table(
        "rejected_facts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("source_locator", sa.Text(), nullable=False),
        sa.Column("reason", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["normalization_runs.id"],
            name=op.f("fk_rejected_facts_run_id_normalization_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rejected_facts")),
        sa.UniqueConstraint("run_id", "source_locator", name=op.f("uq_rejected_facts_run_id")),
    )
    op.create_table(
        "financial_facts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("filing_id", sa.UUID(), nullable=False),
        sa.Column("statement_id", sa.UUID(), nullable=False),
        sa.Column("taxonomy", sa.String(length=80), nullable=False),
        sa.Column("concept", sa.String(length=256), nullable=False),
        sa.Column("value", sa.Numeric(), nullable=False),
        sa.Column("unit", sa.String(length=80), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("period_basis", sa.String(length=20), nullable=False),
        sa.Column("filing_fiscal_year", sa.Integer(), nullable=True),
        sa.Column("filing_fiscal_period", sa.String(length=12), nullable=True),
        sa.Column("reported_available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("availability_basis", sa.String(length=32), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("normalization_version", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "value NOT IN ('NaN'::numeric,'Infinity'::numeric,'-Infinity'::numeric)",
            name=op.f("ck_financial_facts_finite"),
        ),
        sa.CheckConstraint(
            "period_start IS NULL OR period_start <= period_end",
            name=op.f("ck_financial_facts_period_order"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_financial_facts_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["filing_id"], ["filings.id"], name=op.f("fk_financial_facts_filing_id_filings")
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["financial_statements.id"],
            name=op.f("fk_financial_facts_statement_id_financial_statements"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_facts")),
        sa.UniqueConstraint("fingerprint", name=op.f("uq_financial_facts_fingerprint")),
    )
    op.create_index(
        "ix_facts_lookup",
        "financial_facts",
        ["company_id", "concept", "period_basis", "period_end"],
        unique=False,
    )
    op.create_table(
        "fact_sources",
        sa.Column("fact_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("source_locator", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fact_id"],
            ["financial_facts.id"],
            name=op.f("fk_fact_sources_fact_id_financial_facts"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_objects.id"],
            name=op.f("fk_fact_sources_source_id_source_objects"),
        ),
        sa.PrimaryKeyConstraint(
            "fact_id", "source_id", "source_locator", name=op.f("pk_fact_sources")
        ),
    )
    op.create_table(
        "metric_inputs",
        sa.Column("metric_id", sa.UUID(), nullable=False),
        sa.Column("operand_name", sa.String(length=80), nullable=False),
        sa.Column("fact_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fact_id"],
            ["financial_facts.id"],
            name=op.f("fk_metric_inputs_fact_id_financial_facts"),
        ),
        sa.ForeignKeyConstraint(
            ["metric_id"],
            ["financial_metrics.id"],
            name=op.f("fk_metric_inputs_metric_id_financial_metrics"),
        ),
        sa.PrimaryKeyConstraint("metric_id", "operand_name", name=op.f("pk_metric_inputs")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("metric_inputs")
    op.drop_table("fact_sources")
    op.drop_table("financial_facts")
    op.drop_table("rejected_facts")
    op.drop_table("financial_statements")
    op.drop_table("snapshot_observations")
    op.drop_table("securities")
    op.drop_table("normalization_runs")
    op.drop_table("financial_metrics")
    op.drop_table("filings")
    op.drop_table("source_objects")
    op.drop_table("data_source_state")
    op.drop_table("data_fetch_logs")
    op.drop_table("companies")
    # ### end Alembic commands ###
