"""research_workflow"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "10bc42a3cfb1"
down_revision = "599d1b9a7129"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_error", sa.String(length=80), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('QUEUED','RUNNING','FAILED','COMPLETED','NEEDS_CLARIFICATION')",
            name=op.f("ck_workflow_jobs_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_jobs")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workflow_jobs")
    # ### end Alembic commands ###
