"""basic_research"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "1486d73c77a0"
down_revision = "9fc509aa38a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question_hash", sa.String(length=64), nullable=False),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("generation_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("prompt_version", sa.Text(), nullable=False),
        sa.Column("model_provider", sa.Text(), nullable=False),
        sa.Column("model_name", sa.Text(), nullable=True),
        sa.Column("retrieval_ms", sa.Float(), nullable=False),
        sa.Column("generation_ms", sa.Float(), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["generation_id"],
            ["index_generations.id"],
            name=op.f("fk_research_runs_generation_id_index_generations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_runs")),
    )
    op.create_table(
        "research_citations",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("claim_id", sa.String(length=12), nullable=False),
        sa.Column("generation_id", sa.UUID(), nullable=False),
        sa.Column("chunk_id", sa.UUID(), nullable=False),
        sa.Column("exact_quote", sa.Text(), nullable=False),
        sa.Column("quote_hash", sa.String(length=64), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column("verification_status", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["generation_id", "chunk_id"],
            ["generation_chunks.generation_id", "generation_chunks.chunk_id"],
            name=op.f("fk_research_citations_generation_id_generation_chunks"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.id"],
            name=op.f("fk_research_citations_run_id_research_runs"),
        ),
        sa.PrimaryKeyConstraint("run_id", "claim_id", name=op.f("pk_research_citations")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("research_citations")
    op.drop_table("research_runs")
    # ### end Alembic commands ###
