"""calculated_metrics"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "599d1b9a7129"
down_revision = "714683a5d9fb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "financial_metrics",
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("metric_inputs", sa.Column("input_metric_id", sa.UUID(), nullable=True))
    op.alter_column("metric_inputs", "fact_id", existing_type=sa.UUID(), nullable=True)
    op.create_foreign_key(
        op.f("fk_metric_inputs_input_metric_id_financial_metrics"),
        "metric_inputs",
        "financial_metrics",
        ["input_metric_id"],
        ["id"],
    )
    op.create_check_constraint(
        op.f("ck_metric_inputs_one_input"),
        "metric_inputs",
        "(fact_id IS NULL) <> (input_metric_id IS NULL)",
    )
    op.create_check_constraint(
        op.f("ck_metric_inputs_not_self"), "metric_inputs", "metric_id <> input_metric_id"
    )
    # ### end Alembic commands ###


def downgrade():
    if op.get_bind().scalar(
        sa.text("SELECT EXISTS (SELECT 1 FROM metric_inputs WHERE input_metric_id IS NOT NULL)")
    ):
        raise RuntimeError("Cannot downgrade while derived metric dependencies exist")
    op.drop_constraint(op.f("ck_metric_inputs_not_self"), "metric_inputs", type_="check")
    op.drop_constraint(op.f("ck_metric_inputs_one_input"), "metric_inputs", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_metric_inputs_input_metric_id_financial_metrics"),
        "metric_inputs",
        type_="foreignkey",
    )
    op.alter_column("metric_inputs", "fact_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("metric_inputs", "input_metric_id")
    op.drop_column("financial_metrics", "response")
    # ### end Alembic commands ###
