"""hybrid_retrieval"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "714683a5d9fb"
down_revision = "1486d73c77a0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lexical_generations",
        sa.Column("generation_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("corpus_manifest", sa.String(length=64), nullable=False),
        sa.Column("index_hash", sa.String(length=64), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["generation_id"],
            ["index_generations.id"],
            name=op.f("fk_lexical_generations_generation_id_index_generations"),
        ),
        sa.PrimaryKeyConstraint("generation_id", name=op.f("pk_lexical_generations")),
    )
    op.create_table(
        "lexical_chunks",
        sa.Column("generation_id", sa.UUID(), nullable=False),
        sa.Column("chunk_id", sa.UUID(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("terms", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("length", sa.Integer(), nullable=False),
        sa.CheckConstraint("length >= 0", name=op.f("ck_lexical_chunks_length")),
        sa.ForeignKeyConstraint(
            ["generation_id", "chunk_id"],
            ["generation_chunks.generation_id", "generation_chunks.chunk_id"],
            name=op.f("fk_lexical_chunks_generation_id_generation_chunks"),
        ),
        sa.ForeignKeyConstraint(
            ["generation_id"],
            ["lexical_generations.generation_id"],
            name=op.f("fk_lexical_chunks_generation_id_lexical_generations"),
        ),
        sa.PrimaryKeyConstraint("generation_id", "chunk_id", name=op.f("pk_lexical_chunks")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lexical_chunks")
    op.drop_table("lexical_generations")
    # ### end Alembic commands ###
