"""filing_index"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "9fc509aa38a2"
down_revision = "0001_financial"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embedding_cache",
        sa.Column("model_key", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("vector", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("model_key", "content_hash", name=op.f("pk_embedding_cache")),
    )
    op.create_table(
        "index_generations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("collection_name", sa.Text(), nullable=False),
        sa.Column("manifest_hash", sa.String(length=64), nullable=False),
        sa.Column("model_key", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.Text(), nullable=False),
        sa.Column("model_revision", sa.String(length=40), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('building', 'validated', 'active', 'retired')",
            name=op.f("ck_index_generations_state"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_index_generations")),
        sa.UniqueConstraint("collection_name", name=op.f("uq_index_generations_collection_name")),
    )
    op.create_index(
        "uq_index_generations_active",
        "index_generations",
        ["state"],
        unique=True,
        postgresql_where=sa.text("state = 'active'"),
    )
    op.create_table(
        "filing_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("filing_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("document_hash", sa.String(length=64), nullable=False),
        sa.Column("parsed_hash", sa.String(length=64), nullable=False),
        sa.Column("parser_version", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["filing_id"], ["filings.id"], name=op.f("fk_filing_documents_filing_id_filings")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_objects.id"],
            name=op.f("fk_filing_documents_source_id_source_objects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_filing_documents")),
        sa.UniqueConstraint("filing_id", "parsed_hash", name=op.f("uq_filing_documents_filing_id")),
    )
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("section", sa.Text(), nullable=True),
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("chunker_version", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "start_offset >= 0 AND end_offset > start_offset",
            name=op.f("ck_document_chunks_offsets"),
        ),
        sa.CheckConstraint("token_count > 0", name=op.f("ck_document_chunks_token_count")),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["filing_documents.id"],
            name=op.f("fk_document_chunks_document_id_filing_documents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint(
            "document_id", "chunker_version", "ordinal", name=op.f("uq_document_chunks_document_id")
        ),
    )
    op.create_table(
        "generation_chunks",
        sa.Column("generation_id", sa.UUID(), nullable=False),
        sa.Column("chunk_id", sa.UUID(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["document_chunks.id"],
            name=op.f("fk_generation_chunks_chunk_id_document_chunks"),
        ),
        sa.ForeignKeyConstraint(
            ["generation_id"],
            ["index_generations.id"],
            name=op.f("fk_generation_chunks_generation_id_index_generations"),
        ),
        sa.PrimaryKeyConstraint("generation_id", "chunk_id", name=op.f("pk_generation_chunks")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("generation_chunks")
    op.drop_table("document_chunks")
    op.drop_table("filing_documents")
    op.drop_index(
        "uq_index_generations_active",
        table_name="index_generations",
        postgresql_where=sa.text("state = 'active'"),
    )
    op.drop_table("index_generations")
    op.drop_table("embedding_cache")
    # ### end Alembic commands ###
